CREATE DATABASE chalk_mvp;
\c chalk_mvp;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "STUDENT" (
  ID VARCHAR(255) NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  UNIVERSITY VARCHAR(500) NOT NULL,
  YEAR_OF_GRADUATION INTEGER NOT NULL,
  SKILLS VARCHAR(20) ARRAY,
  DESCRIPTION VARCHAR(500),
  DEGREE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "BOOKMARKS" (
  EMAIL VARCHAR(255) NOT NULL REFERENCES public."STUDENT"(EMAIL), 
  STUDENT_EMAILS VARCHAR(255) ARRAY
);
